/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-RC"
 * 	found in "./e2sm-kpm-rc.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -pdu=auto -gen-PER -gen-OER -no-gen-example -D .`
 */

#include "E2SM-RC-ControlHeader-Format1.h"

#include "RRMPolicyRatioList.h"
asn_TYPE_member_t asn_MBR_E2SM_RC_ControlHeader_Format1_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_ControlHeader_Format1, ueId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_Identity,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ueId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_ControlHeader_Format1, ric_ControlStyle_Type),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_Style_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-ControlStyle-Type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_ControlHeader_Format1, ric_ControlAction_ID),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_ControlAction_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-ControlAction-ID"
		},
	{ ATF_POINTER, 1, offsetof(struct E2SM_RC_ControlHeader_Format1, rrmPolicyList),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRMPolicyRatioList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rrmPolicyList"
		},
};
static const int asn_MAP_E2SM_RC_ControlHeader_Format1_oms_1[] = { 3 };
static const ber_tlv_tag_t asn_DEF_E2SM_RC_ControlHeader_Format1_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_E2SM_RC_ControlHeader_Format1_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ueId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ric-ControlStyle-Type */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ric-ControlAction-ID */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* rrmPolicyList */
};
asn_SEQUENCE_specifics_t asn_SPC_E2SM_RC_ControlHeader_Format1_specs_1 = {
	sizeof(struct E2SM_RC_ControlHeader_Format1),
	offsetof(struct E2SM_RC_ControlHeader_Format1, _asn_ctx),
	asn_MAP_E2SM_RC_ControlHeader_Format1_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_E2SM_RC_ControlHeader_Format1_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_E2SM_RC_ControlHeader_Format1 = {
	"E2SM-RC-ControlHeader-Format1",
	"E2SM-RC-ControlHeader-Format1",
	&asn_OP_SEQUENCE,
	asn_DEF_E2SM_RC_ControlHeader_Format1_tags_1,
	sizeof(asn_DEF_E2SM_RC_ControlHeader_Format1_tags_1)
		/sizeof(asn_DEF_E2SM_RC_ControlHeader_Format1_tags_1[0]), /* 1 */
	asn_DEF_E2SM_RC_ControlHeader_Format1_tags_1,	/* Same as above */
	sizeof(asn_DEF_E2SM_RC_ControlHeader_Format1_tags_1)
		/sizeof(asn_DEF_E2SM_RC_ControlHeader_Format1_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_E2SM_RC_ControlHeader_Format1_1,
	4,	/* Elements count */
	&asn_SPC_E2SM_RC_ControlHeader_Format1_specs_1	/* Additional specs */
};

