/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-RC"
 * 	found in "./e2sm-kpm-rc.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -pdu=auto -gen-PER -gen-OER -no-gen-example -D .`
 */

#ifndef	_RRMPolicyRatioGroup_H_
#define	_RRMPolicyRatioGroup_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RRMPolicy.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RRMPolicyRatioGroup */
typedef struct RRMPolicyRatioGroup {
	RRMPolicy_t	 rrmPolicy;
	long	*minPRBPolicyRatio	/* OPTIONAL */;
	long	*maxPRBPolicyRatio	/* OPTIONAL */;
	long	*dedicatedPRBPolicyRatio	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRMPolicyRatioGroup_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRMPolicyRatioGroup;
extern asn_SEQUENCE_specifics_t asn_SPC_RRMPolicyRatioGroup_specs_1;
extern asn_TYPE_member_t asn_MBR_RRMPolicyRatioGroup_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _RRMPolicyRatioGroup_H_ */
#include <asn_internal.h>
