/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-RC"
 * 	found in "./e2sm-kpm-rc.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -pdu=auto -gen-PER -gen-OER -no-gen-example -D .`
 */

#ifndef	_RRMPolicy_H_
#define	_RRMPolicy_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RRMPolicyMember;

/* RRMPolicy */
typedef struct RRMPolicy {
	struct RRMPolicy__rrmPolicyMemberList {
		A_SEQUENCE_OF(struct RRMPolicyMember) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} rrmPolicyMemberList;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRMPolicy_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRMPolicy;
extern asn_SEQUENCE_specifics_t asn_SPC_RRMPolicy_specs_1;
extern asn_TYPE_member_t asn_MBR_RRMPolicy_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _RRMPolicy_H_ */
#include <asn_internal.h>
