/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-RC"
 * 	found in "./e2sm-kpm-rc.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -pdu=auto -gen-PER -gen-OER -no-gen-example -D .`
 */

#include "RRMPolicyRatioGroup.h"

static int
memb_minPRBPolicyRatio_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 100)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_maxPRBPolicyRatio_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 100)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_dedicatedPRBPolicyRatio_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 100)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_minPRBPolicyRatio_constr_3 CC_NOTUSED = {
	{ 1, 1 }	/* (0..100) */,
	-1};
static asn_per_constraints_t asn_PER_memb_minPRBPolicyRatio_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  0,  100 }	/* (0..100) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_maxPRBPolicyRatio_constr_4 CC_NOTUSED = {
	{ 1, 1 }	/* (0..100) */,
	-1};
static asn_per_constraints_t asn_PER_memb_maxPRBPolicyRatio_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  0,  100 }	/* (0..100) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_dedicatedPRBPolicyRatio_constr_5 CC_NOTUSED = {
	{ 1, 1 }	/* (0..100) */,
	-1};
static asn_per_constraints_t asn_PER_memb_dedicatedPRBPolicyRatio_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  0,  100 }	/* (0..100) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_RRMPolicyRatioGroup_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRMPolicyRatioGroup, rrmPolicy),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRMPolicy,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rrmPolicy"
		},
	{ ATF_POINTER, 3, offsetof(struct RRMPolicyRatioGroup, minPRBPolicyRatio),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_minPRBPolicyRatio_constr_3, &asn_PER_memb_minPRBPolicyRatio_constr_3,  memb_minPRBPolicyRatio_constraint_1 },
		0, 0, /* No default value */
		"minPRBPolicyRatio"
		},
	{ ATF_POINTER, 2, offsetof(struct RRMPolicyRatioGroup, maxPRBPolicyRatio),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_maxPRBPolicyRatio_constr_4, &asn_PER_memb_maxPRBPolicyRatio_constr_4,  memb_maxPRBPolicyRatio_constraint_1 },
		0, 0, /* No default value */
		"maxPRBPolicyRatio"
		},
	{ ATF_POINTER, 1, offsetof(struct RRMPolicyRatioGroup, dedicatedPRBPolicyRatio),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_dedicatedPRBPolicyRatio_constr_5, &asn_PER_memb_dedicatedPRBPolicyRatio_constr_5,  memb_dedicatedPRBPolicyRatio_constraint_1 },
		0, 0, /* No default value */
		"dedicatedPRBPolicyRatio"
		},
};
static const int asn_MAP_RRMPolicyRatioGroup_oms_1[] = { 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_RRMPolicyRatioGroup_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RRMPolicyRatioGroup_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrmPolicy */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* minPRBPolicyRatio */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* maxPRBPolicyRatio */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* dedicatedPRBPolicyRatio */
};
asn_SEQUENCE_specifics_t asn_SPC_RRMPolicyRatioGroup_specs_1 = {
	sizeof(struct RRMPolicyRatioGroup),
	offsetof(struct RRMPolicyRatioGroup, _asn_ctx),
	asn_MAP_RRMPolicyRatioGroup_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_RRMPolicyRatioGroup_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RRMPolicyRatioGroup = {
	"RRMPolicyRatioGroup",
	"RRMPolicyRatioGroup",
	&asn_OP_SEQUENCE,
	asn_DEF_RRMPolicyRatioGroup_tags_1,
	sizeof(asn_DEF_RRMPolicyRatioGroup_tags_1)
		/sizeof(asn_DEF_RRMPolicyRatioGroup_tags_1[0]), /* 1 */
	asn_DEF_RRMPolicyRatioGroup_tags_1,	/* Same as above */
	sizeof(asn_DEF_RRMPolicyRatioGroup_tags_1)
		/sizeof(asn_DEF_RRMPolicyRatioGroup_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RRMPolicyRatioGroup_1,
	4,	/* Elements count */
	&asn_SPC_RRMPolicyRatioGroup_specs_1	/* Additional specs */
};

