/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-RC"
 * 	found in "e2sm-kpm-rc.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -pdu=auto -gen-PER -gen-OER -no-gen-example -D .`
 */

#ifndef	_SlicePRBQuota_H_
#define	_SlicePRBQuota_H_


#include <asn_application.h>

/* Including external dependencies */
#include "S-NSSAI.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SlicePRBQuota */
typedef struct SlicePRBQuota {
	S_NSSAI_t	 sliceID;
	long	 minPRBRatio;
	long	 maxPRBRatio;
	long	 dedicatePRBRatio;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SlicePRBQuota_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SlicePRBQuota;
extern asn_SEQUENCE_specifics_t asn_SPC_SlicePRBQuota_specs_1;
extern asn_TYPE_member_t asn_MBR_SlicePRBQuota_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _SlicePRBQuota_H_ */
#include <asn_internal.h>
